models/Movie.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "movies".
 *
 * @property int $id
 * @property string|null $title
 * @property string|null $link
 * @property string|null $description
 * @property string|null $pubDate
 * @property string|null $image
 */
class Movie extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'movies';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['description'], 'string'],
            [['pubDate'], 'integer'],
            [['title', 'link', 'image'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'Title'),
            'link' => Yii::t('app', 'Link'),
            'description' => Yii::t('app', 'Description'),
            'pubDate' => Yii::t('app', 'Pub Date'),
            'image' => Yii::t('app', 'Image'),
        ];
    }
}

controllers/MovieController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\NotFoundHttpException;
use app\models\Movie;

class MovieController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $movies = Movie::find()->all();

        return $this->render('index', [
            'movies' => $movies,
        ]);
    }

    public function actionView(int $id)
    {
        $movie = Movie::findOne(['id' => $id]);

        if($movie === null) {
            throw new NotFoundHttpException(Yii::t('app', 'Movie not found'));
        }

        return $this->render('view', [
            'movie' => $movie,
        ]);
    }
}

views/movie/index.php
<?php
use yii\helpers\Html;
use app\models\Like;
use app\widgets\LikeWidget;
/* @var $this yii\web\View */

$this->title = Yii::t('app', 'Movies list');
?>

<h1><?= $this->title ?></h1>
<div class="row">
    <?php foreach($movies as $movie): ?>
        <div class="col-xs-12 col-sm-6">
            <div class="thumbnail movie-card">
                <img src="<?= $movie->image ?>">
                <div class="caption">
                    <h3>
                        <?= Html::a($movie->title, ['movie/view', 'id' => $movie->id]) ?>
                    </h3>
                    <div class="movie-description" ><?= $movie->description ?></div>
                    <div class="movie-actions"> 
                        <?= Html::a(Yii::t('app', 'View'), ['movie/view', 'id' => $movie->id], [
                            'class' => 'btn btn-primary'
                        ]) ?>
                        <div style="float: right;">
                            <?= LikeWidget::widget([
                                'entity' => $movie,
                                'entityName' => 'movie',
                            ]) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach; ?>
</div>

views/movie/view.php
<?php
use yii\helpers\Html;
use app\widgets\LikeWidget;
/* @var $this yii\web\View */

$this->title = $movie->title;
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="media">
        <div class="media-left media-middle">
            <img class="media-object" src="<?= $movie->image ?>">
        </div>
        <div class="media-body">
            <h4 class="media-heading"><?= $movie->title ?></h4>
            <p>Trailer link: <a href="<?= $movie->link ?>" target="_blank"><?= $movie->link ?></a></p>
            <p>Published at: <span class="text-muted"><?= Yii::$app->formatter->asDatetime($movie->pubDate) ?></span></p>
            <p><?= $movie->description ?></p>
        </div>
    </div>
    <div class="movie-view-actions">
        <?= LikeWidget::widget([
            'entity' => $movie,
            'entityName' => 'movie',
        ]) ?>
    </div>
</div>